### ISSUE TITLE
lil file for AIX brokers

### ISSUE THREAD

**Issue by gjose9** [ot4i/iib-stats-writer-statsd#1]
Is it possible to get the compiled file for AIX?

**Comment by tdolby-at-uk-ibm-com** [comment]
Should be possible, though it might have to be built with gcc instead of xlC and therefore require installation of some RPMs as well as the lil.

Which version of AIX are you planning on using?

**Comment by gjose9** [comment]
Hi,
Thank you so much for your response. Below the environment info:
-------------------- >>>
$ oslevel
7.1.0.0
$ oslevel -r
7100-04

and the IIB version is 10.0.0.6
-------------------- <<<
It would be great help if you could help in this.
Thank you!

Jose.

**Comment by tdolby-at-uk-ibm-com** [comment]
An AIX version (or rather, two versions) is now available at https://github.com/tdolby-at-uk-ibm-com/iib-stats-writer-statsd (repo forked for the moment but will be merged into the main codebase if the LILs function correctly) in the prebuilt/aix7.1 directory.

The xlC13 variant will work without further prereqs (assuming xlC.rte is up-to-date), but was built with a compatibility layer that implements a few pieces of the C++11 standard that the compiler doesn't yet handle; the gcc630 version requires no such changes, but will require RPMs to be installed (see README.md in the directory).

Feedback most welcome, regardless of success! Worth trying the xlC variant first, and using the GCC one if anything odd happens. I've tested this with the grafana Docker image mentioned in the repo, and it feeds statistics correctly; the only slight issue is that you can't run the Docker image on the AIX machine, so port 8125/udp has to be exposed on the host interface.

**Comment by gjose9** [comment]
Dear Trevor, Thank you for the help. Will test these files and will send you the feedback.

Thanks a ton!

Regards,
Jose.

**Comment by gjose9** [comment]
Hi Trevor,

Thank you for the help. Yes, the LIL compiled for AIX is working as expected. It's being tested in our test environment.

Thanks & Regards,
Jose.
